---
name: "Validate PR"

"on":
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: commit-check/commit-check-action@a61779784a953fd9047c001c102cfeac5cf26964 # v2.17.1
        with:
          message: false
          branch: false
          pr-title: true
          job-summary: true
          pr-comments: true
        env:
          CCHK_ALLOW_COMMIT_TYPES: "build,chore,ci,docs,feat,fix,perf,refactor,revert,security,style,test"
